export const initialState = {
  wallet: { value: 0,
    description: '',
    currency: 'USD',
    method: 'Dinheiro',
    tag: 'Alimentação',
    currencies: ['USD',
      'CAD',
      'GBP',
      'ARS',
      'BTC',
      'LTC',
      'EUR',
      'JPY',
      'CHF',
      'AUD',
      'CNY',
      'ILS',
      'ETH',
      'XRP',
      'DOGE'],
    expenses: [],
  },

};
const created = '2023-02-03 18:59:53';

export const initialStateTwo = {

  user: {
    email: 'dasd@dasd.com.br',
  },
  wallet: {
    currencies: [
      'USD',
      'CAD',
      'GBP',
      'ARS',
      'BTC',
      'LTC',
      'EUR',
      'JPY',
      'CHF',
      'AUD',
      'CNY',
      'ILS',
      'ETH',
      'XRP',
      'DOGE',
    ],
    expenses: [
      {
        value: '10',
        description: '10 dólares',
        currency: 'USD',
        method: 'Dinheiro',
        tag: 'Alimentação',
        exchangeRates: {
          USD: {
            code: 'USD',
            codein: 'BRL',
            name: 'Dólar Americano/Real Brasileiro',
            high: '5.1587',
            low: '5.0509',
            varBid: '0.1021',
            pctChange: '2.02',
            bid: '5.1522',
            ask: '5.1527',
            timestamp: '1675461593',
            create_date: created,
          },
          USDT: {
            code: 'USD',
            codein: 'BRLT',
            name: 'Dólar Americano/Real Brasileiro Turismo',
            high: '5.165',
            low: '5.06',
            varBid: '0.105',
            pctChange: '2.08',
            bid: '5.01',
            ask: '5.32',
            timestamp: '1675451400',
            create_date: created,
          },
          CAD: {
            code: 'CAD',
            codein: 'BRL',
            name: 'Dólar Canadense/Real Brasileiro',
            high: '3.8489',
            low: '3.7764',
            varBid: '0.0526',
            pctChange: '1.39',
            bid: '3.8446',
            ask: '3.8459',
            timestamp: '1675461593',
            create_date: created,
          },
          GBP: {
            code: 'GBP',
            codein: 'BRL',
            name: 'Libra Esterlina/Real Brasileiro',
            high: '6.2772',
            low: '6.1537',
            varBid: '0.0381',
            pctChange: '0.62',
            bid: '6.2099',
            ask: '6.2126',
            timestamp: '1675461590',
            create_date: created,
          },
          ARS: {
            code: 'ARS',
            codein: 'BRL',
            name: 'Peso Argentino/Real Brasileiro',
            high: '0.0274',
            low: '0.0269',
            varBid: '0.0005',
            pctChange: '1.86',
            bid: '0.0274',
            ask: '0.0274',
            timestamp: '1675461593',
            create_date: created,
          },
          BTC: {
            code: 'BTC',
            codein: 'BRL',
            name: 'Bitcoin/Real Brasileiro',
            high: '121647',
            low: '118601',
            varBid: '915',
            pctChange: '0.76',
            bid: '120525',
            ask: '120997',
            timestamp: '1675463262',
            create_date: created,
          },
          LTC: {
            code: 'LTC',
            codein: 'BRL',
            name: 'Litecoin/Real Brasileiro',
            high: '519',
            low: '480.5',
            varBid: '7.87',
            pctChange: '1.57',
            bid: '510.5',
            ask: '514.9',
            timestamp: '1675463265',
            create_date: created,
          },
          EUR: {
            code: 'EUR',
            codein: 'BRL',
            name: 'Euro/Real Brasileiro',
            high: '5.5966',
            low: '5.4963',
            varBid: '0.0526',
            pctChange: '0.95',
            bid: '5.5613',
            ask: '5.5639',
            timestamp: '1675461593',
            create_date: created,
          },
          JPY: {
            code: 'JPY',
            codein: 'BRL',
            name: 'Iene Japonês/Real Brasileiro',
            high: '0.03987',
            low: '0.03901',
            varBid: '0',
            pctChange: '0',
            bid: '0.03926',
            ask: '0.03929',
            timestamp: '1675461585',
            create_date: created,
          },
          CHF: {
            code: 'CHF',
            codein: 'BRL',
            name: 'Franco Suíço/Real Brasileiro',
            high: '5.6063',
            low: '5.5093',
            varBid: '0.0335',
            pctChange: '0.61',
            bid: '5.5621',
            ask: '5.5645',
            timestamp: '1675461593',
            create_date: created,
          },
          AUD: {
            code: 'AUD',
            codein: 'BRL',
            name: 'Dólar Australiano/Real Brasileiro',
            high: '3.6131',
            low: '3.5494',
            varBid: '-0.0067',
            pctChange: '-0.19',
            bid: '3.5664',
            ask: '3.5677',
            timestamp: '1675461593',
            create_date: created,
          },
          CNY: {
            code: 'CNY',
            codein: 'BRL',
            name: 'Yuan Chinês/Real Brasileiro',
            high: '0.7612',
            low: '0.7521',
            varBid: '0.0103',
            pctChange: '1.37',
            bid: '0.7605',
            ask: '0.7605',
            timestamp: '1675461244',
            create_date: created,
          },
          ILS: {
            code: 'ILS',
            codein: 'BRL',
            name: 'Novo Shekel Israelense/Real Brasileiro',
            high: '1.5053',
            low: '1.4875',
            varBid: '0.0167',
            pctChange: '1.13',
            bid: '1.502',
            ask: '1.5021',
            timestamp: '1675461546',
            create_date: created,
          },
          ETH: {
            code: 'ETH',
            codein: 'BRL',
            name: 'Ethereum/Real Brasileiro',
            high: '8599.97',
            low: '8256.22',
            varBid: '150.73',
            pctChange: '1.8',
            bid: '8512.12',
            ask: '8553.74',
            timestamp: '1675463265',
            create_date: created,
          },
          XRP: {
            code: 'XRP',
            codein: 'BRL',
            name: 'XRP/Real Brasileiro',
            high: '2.12',
            low: '2.07',
            varBid: '0.02',
            pctChange: '1.13',
            bid: '2.11',
            ask: '2.12',
            timestamp: '1675463167',
            create_date: created,
          },
          DOGE: {
            code: 'DOGE',
            codein: 'BRL',
            name: 'Dogecoin/Real Brasileiro',
            high: '0.47882',
            low: '0.45854',
            varBid: '0.01132',
            pctChange: '2.43',
            bid: '0.47708',
            ask: '0.47708',
            timestamp: '1675463238',
            create_date: created,
          },
        },
        id: 1,
      },
    ],

  },
};
